### ISSUE TITLE
I2S_BRIDGE on ESP32 S3

### ISSUE THREAD

**Issue by miky2k** [benzino77/tasmocompiler#472]
I2S audio from tasmota documentation need two libraries : lib_extra_dirs = lib/lib_audio, lib/libesp32_audio

but all I2S define compile well on tasmocompiler 13.3.0  (tasmota 15.3) except I2S_BRIDGE that give in the linker 

undefined reference to `_Z15i2s_bridge_loopv'  .

I ask if is possible to add full audio flag (USE_I2S_AUDIO and other audio related mic,bridge,webradio ecc ecc) to features select.
